<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>18d29ca0-203e-423e-9f83-fbd826cf858f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.fw-normal.d-inline-flex.align-items-center.px-4.py-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>440b4d58-4044-4ed6-90f9-e4094262f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>979c46f0-2f3e-4b47-952b-afd6366fd868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success fw-normal d-inline-flex align-items-center px-4 py-2</value>
      <webElementGuid>b7f6c01c-ace2-4e90-a4d4-664afc664d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign In </value>
      <webElementGuid>3c7cf115-4a01-4f4c-ba4a-fe78c8934966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c191-0&quot;]/div[@class=&quot;ng-tns-c191-0&quot;]/app-site-header[@class=&quot;ng-tns-c191-0&quot;]/header[@class=&quot;site-header&quot;]/nav[@class=&quot;header-top&quot;]/div[@class=&quot;navbar navbar-expand-lg px-0&quot;]/div[@class=&quot;container py-1&quot;]/div[@class=&quot;my-2&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;btn btn-success fw-normal d-inline-flex align-items-center px-4 py-2&quot;]</value>
      <webElementGuid>8c784100-390c-4057-b815-14f76fa249d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>af96bf1e-6a90-4f11-84da-81b724278c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email: info@nimc.gov.ng'])[1]/following::button[1]</value>
      <webElementGuid>44e7530b-d1eb-4126-8517-5e9a6d52f78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/preceding::button[1]</value>
      <webElementGuid>60e2a4d9-12cb-42ab-9433-71be11671928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERTIFICATE OF IDENTITY'])[1]/preceding::button[1]</value>
      <webElementGuid>83fdea9b-dd31-468d-b315-bac352488af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>cc3c76e1-8e4f-4d03-bc55-4ea72b5ecbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6eac2c15-4f31-4c9c-8563-b0a1c34465aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Sign In ' or . = ' Sign In ')]</value>
      <webElementGuid>3f9fb746-21d3-46d0-8fdb-76f24af656ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
